

int CreateTempQuestCharacters(int n)
{
	ref ch;

	makeref(ch,Characters[n]);			// Ethilrede Claar - пират, который продал в рабство одного из наших офицеров () Leborio Drago
	ch.name 	= "Этильред";
	ch.lastname 	= "Дюбуа";
	ch.id		= "Ethilrede Claar";
	ch.model = "corsar2";
	ch.sex = "man";
	ch.sound_type = "pirate";
	ch.Ship.AI.GroupName = "Ethilrede Claar";
	ch.Ship.AI.Task = "attack";
	ch.nation = PIRATE;
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "none";
	ch.location.group = "Quest_ships";
	ch.location.locator = "quest_ship_11";
	ch.Dialog.Filename = "Gyles Dubois_dialog.c";
	ch.Ship.Name = "Neptunus";
	ch.Ship.Type = SHIP_CORVETTE_SPAIN;
	ch.Ship.Stopped = true;
	ch.Ship.Cannons.Type = CANNON_TYPE_CANNON_LBS24;
	ch.rank 	= 1;
	ch.reputation = "22";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "4";
	ch.skill.Sailing = "5";
	ch.skill.Accuracy = "4";
	ch.skill.Cannons = "6";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "2";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetMerchantType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_NoRebirthEnable(ch);
	ch.greeting = "Gr_Gyles Dubois";
	n = n + 1;

	makeref(ch,Characters[n]);			// Stephan Bonser - контрабандист на пляже редмонда
	ch.name 	= "Стефан";
	ch.lastname 	= "Бонсер";
	ch.id		= "Stephan Bonser";
	ch.model = "man4";
	ch.sex = "man";
	ch.sound_type = "pirate";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "none";
	ch.location.group = "goto";
	ch.location.locator = "none";
	ch.Dialog.Filename = "Stephan Bonser_dialog.c";
	ch.greeting = "Gr_Stephan Bonser";
	ch.rank 	= 1;
	ch.reputation = "22";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_NoRebirthEnable(ch);
	n = n + 1;

	makeref(ch,Characters[n]);			// Wilfred Bythesea - так, старый знакомы Блэйза, появляющийся эпизодически
	ch.name 	= "Вильфред";
	ch.lastname 	= "Битезеа";
	ch.id		= "Wilfred Bythesea";
	ch.model = "man4";
	ch.sex = "man";
	ch.sound_type = "seaman";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "none";
	ch.location.group = "goto";
	ch.location.locator = "none";
	ch.Dialog.Filename = "Wilfred Bythesea_dialog.c";
	ch.greeting = "Gr_Wilfred Bythesea";
	ch.rank 	= 1;
	ch.reputation = "22";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.quest.kill_Ogarrio = "0";
	ch.money = "10";
	LAi_SetActorType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_NoRebirthEnable(ch);
	n = n + 1;

	makeref(ch,Characters[n]);			// Oswald Chappel - контрабандист на пляже редмонда
	ch.name 	= "Освальд";
	ch.lastname 	= "Чапель";
	ch.id		= "Oswald Chappel";
	ch.model = "korsar";
	ch.sex = "man";
	ch.sound_type = "seaman";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "none";
	ch.location.group = "goto";
	ch.location.locator = "none";
	ch.Dialog.Filename = "Oswald Chappel_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "22";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "2";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_NoRebirthEnable(ch);
	ch.greeting = "Gr_Oswald Chappel";
	n = n + 1;

	makeref(ch,Characters[n]);			// Gyles Dubois - контрабандист на пляже редмонда
	ch.name 	= "Жиль";
	ch.lastname 	= "Дюбуа";
	ch.id		= "Gyles Dubois";
	ch.model = "fisherman";
	ch.sex = "man";
	ch.sound_type = "seaman";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "none"; //redmond_shore_01
	ch.location.group = "goto";
	ch.location.locator = "none";//locator8
	ch.Dialog.Filename = "Gyles Dubois_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "22";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "4";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_NoRebirthEnable(ch);
	ch.greeting = "Gr_Gyles Dubois";
	n = n + 1;

	makeref(ch,Characters[n]);			// Pirate Captain 01
	ch.name 	= "Хабе";
	ch.lastname 	= "Ораглио";
	ch.id		= "Pirate Captain 01";
	ch.model = "fisherman";
	ch.sex = "man";
	ch.sound_type = "pirate";
	ch.Ship.AI.GroupName = "Enemy_Redmond_Smugglers";
	ch.Ship.AI.Task = "attack";
	ch.nation = PIRATE;
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "none";//"Redmond"; //redmond_shore_01
	ch.location.group = "Quest_ships";
	ch.location.locator = "quest_ship_11";//locator8
	ch.Dialog.Filename = "Gyles Dubois_dialog.c";
	ch.Ship.Name = "Fast death";
	ch.Ship.Type = SHIP_BRIG_PORTUGAL;
	ch.Ship.Stopped = true;
	ch.Ship.Cannons.Type = CANNON_TYPE_CANNON_LBS16;
	ch.rank 	= 1;
	ch.reputation = "22";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "4";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "4";
	ch.skill.Cannons = "3";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetMerchantType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_NoRebirthEnable(ch);
	ch.greeting = "Gr_Gyles Dubois";
	n = n + 1;

	makeref(ch,Characters[n]);			// Pirate Captain 02
	ch.name 	= "Жиль";
	ch.lastname 	= "Дюбуа";
	ch.id		= "Pirate Captain 02";
	ch.model = "fisherman";
	ch.sex = "man";
	ch.sound_type = "pirate";
	LAi_NoRebirthEnable(ch);
	ch.Ship.AI.GroupName = "Enemy_Redmond_Smugglers";
	ch.Ship.AI.Task = "attack";
	ch.nation = PIRATE;
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "none";//"Redmond"; //redmond_shore_01
	ch.location.group = "Quest_ships";
	ch.location.locator = "quest_ship_11";//locator8
	ch.Dialog.Filename = "Gyles Dubois_dialog.c";
	ch.Ship.Name = "Madonna";
	ch.Ship.Type = SHIP_LUGGER_ENGLAND;
	ch.Ship.Stopped = true;
	ch.Ship.Cannons.Type = CANNON_TYPE_CANNON_LBS16;
	ch.rank 	= 1;
	ch.reputation = "22";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "4";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "3";
	ch.skill.Cannons = "4";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetMerchantType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	ch.greeting = "Gr_Gyles Dubois";
	n = n + 1;

	makeref(ch,Characters[n]);			// Pirate Captain 03
	ch.name 	= "Жиль";
	ch.lastname 	= "Дюбуа";
	ch.id		= "Pirate Captain 03";
	ch.model = "fisherman";
	ch.sex = "man";
	ch.sound_type = "pirate";
	LAi_NoRebirthEnable(ch);
	ch.Ship.AI.GroupName = "Enemy_Redmond_Smugglers";
	ch.Sea.Task = "attack";
	ch.Ship.AI.Task = "attack";
	ch.nation = PIRATE;
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "none";//"Redmond"; //redmond_shore_01
	ch.location.group = "Quest_ships";
	ch.location.locator = "quest_ship_11";//locator8
	ch.Dialog.Filename = "Gyles Dubois_dialog.c";
	ch.Ship.Name = "Madonna";
	ch.Ship.Type = SHIP_BARQUE_FRANCE;
	ch.Ship.Stopped = true;
	ch.Ship.Cannons.Type = CANNON_TYPE_CANNON_LBS16;
	ch.rank 	= 1;
	ch.reputation = "22";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "4";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "3";
	ch.skill.Cannons = "4";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetMerchantType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	ch.greeting = "Gr_Gyles Dubois";
	n = n + 1;

	makeref(ch,Characters[n]);			// Pirate Captain 04
	ch.name 	= "Жиль";
	ch.lastname 	= "Дюбуа";
	ch.id		= "Pirate Captain 04";
	ch.model = "fisherman";
	ch.sex = "man";
	ch.sound_type = "pirate";
	LAi_NoRebirthEnable(ch);
	ch.Ship.AI.GroupName = "Enemy_Redmond_Smugglers_Away";
	ch.Ship.AI.Task = "runaway";
	ch.nation = PIRATE;
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "none";//"Redmond"; //redmond_shore_01
	ch.location.group = "Quest_ships";
	ch.location.locator = "quest_ship_3";//locator8
	ch.Dialog.Filename = "Gyles Dubois_dialog.c";
	ch.Ship.Name = "Madonna";
	ch.Ship.Type = SHIP_CARAVEL_HOLLAND;
	ch.Ship.Stopped = true;
	ch.Ship.Cannons.Type = CANNON_TYPE_CANNON_LBS16;
	ch.rank 	= 1;
	ch.reputation = "22";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "2";
	ch.skill.Sailing = "2";
	ch.skill.Accuracy = "5";
	ch.skill.Cannons = "4";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetMerchantType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	ch.greeting = "Gr_Gyles Dubois";
	n = n + 1;

	makeref(ch,Characters[n]);			// Soldier for fight_01
	ch.name 	= "Солдат";
	ch.lastname 	= "";
	ch.id		= "Soldier for fight_01";
	ch.model = "soldier_fra";
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_NoRebirthEnable(ch);
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "none"
	ch.location.group = "reload";
	ch.location.locator = "locator2";
	ch.Dialog.Filename = "falaise de fleur soldier_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "52";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "2";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "5";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	ch.greeting = "Gr_falaise de fleur soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			// Soldier for fight_02
	ch.name 	= "Солдат";
	ch.lastname 	= "";
	ch.id		= "Soldier for fight_02";
	ch.model = "soldier_fra";
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_NoRebirthEnable(ch);
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "none"
	ch.location.group = "reload";
	ch.location.locator = "locator2";
	ch.Dialog.Filename = "falaise de fleur soldier_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "52";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "4";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "5";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	ch.greeting = "Gr_falaise de fleur soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			// Eng Captain Near FdF
	ch.name 	= "Симон";
	ch.lastname 	= "Бландел";
	ch.id		= "Eng Captain Near FdF";
	ch.model = "Offic_eng";
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_NoRebirthEnable(ch);
	ch.Ship.AI.GroupName = "England_Captain_Near_FdF";
	ch.Ship.AI.Task = "runaway";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "none"
	ch.location.group = "Quest_ships";
	ch.location.locator = "quest_ship_7";
	ch.Dialog.Filename = "falaise de fleur soldier_dialog.c";
	ch.nation = PIRATE;
	ch.Ship.Name = "Fast death";
	ch.Ship.Type = SHIP_CORVETTE_PORTUGAL;
	ch.Ship.Stopped = true;
	ch.Ship.Cannons.Type = CANNON_TYPE_CANNON_LBS16;
	ch.rank 	= 1;
	ch.reputation = "52";
	ch.experience = "0";
	ch.skill.Leadership = "4";
	ch.skill.Fencing = "6";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "5";
	ch.skill.Cannons = "3";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	ch.greeting = "Gr_falaise de fleur soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			// Eng Captain who have IDOL
	ch.name 	= "Гарольд";
	ch.lastname 	= "Баррат";
	ch.id		= "Eng Captain Idol";
	ch.model = "Offic_eng";
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_NoRebirthEnable(ch);
	ch.Ship.AI.GroupName = "Idol_Squadron";
	ch.Ship.AI.Task = "runaway";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "none"
	ch.location.group = "Quest_ships";
	ch.location.locator = "quest_ship_7";
	ch.Dialog.Filename = "falaise de fleur soldier_dialog.c";
	ch.nation = ENGLAND;
	ch.Ship.Name = "Arabella";
	ch.Ship.Type = SHIP_FRIGATE_ENGLAND;
	ch.Ship.Stopped = true;
	ch.Ship.Cannons.Type = CANNON_TYPE_CANNON_LBS24;
	ch.rank 	= 1;
	ch.reputation = "52";
	ch.experience = "0";
	ch.skill.Leadership = "4";
	ch.skill.Fencing = "6";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "5";
	ch.skill.Cannons = "3";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	ch.greeting = "Gr_falaise de fleur soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			// France_bukaner_01
	ch.name 	= "Французский_пират_01";
	ch.lastname 	= "";
	ch.id		= "France_bukaner_01";
	ch.model = "man2";
	ch.sex = "man";
	ch.sound_type = "pirate";
	LAi_NoRebirthEnable(ch);
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.Dialog.Filename = "falaise de fleur soldier_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "28";
	Ch.location = "none";
	ch.experience = "35";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "2";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "154";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	ch.greeting = "Gr_falaise de fleur soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			// Danielle_sailor
	ch.name 	= "Моряк";
	ch.lastname 	= "";
	ch.id		= "Danielle_sailor";
	ch.model = "bocman";
	ch.sex = "man";
	ch.sound_type = "seaman";
	LAi_NoRebirthEnable(ch);
	ch.nation = ENGLAND;
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.Dialog.Filename = "Danielle_sailor_dialog.c";
	ch.greeting = "Gr_danielle_sailor";
	ch.rank 	= 1;
	ch.reputation = "28";
	ch.experience = "35";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "2";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.quest.kill_pirate_06 = "";
	ch.money = "154";
	LAi_SetActorType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	n = n + 1;

	makeref(ch,Characters[n]);			// quest_pirate_01
	ch.name 	= "Пират";
	ch.lastname 	= "";
	ch.id		= "quest_pirate_01";
	ch.model = "korsar";
	ch.sex = "man";
	ch.sound_type = "pirate";
	LAi_NoRebirthEnable(ch);
	ch.nation = PIRATE;
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "none"
	ch.location.group = "goto";
	ch.location.locator = "goto4";
	ch.Dialog.Filename = "quest_pirate_01_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "52";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "4";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "5";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetActorType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_NoRebirthEnable(ch);
	n = n + 1;

	makeref(ch,Characters[n]);			// quest_smuggler_01
	ch.name 	= "Контрабандист";
	ch.lastname 	= "";
	ch.id		= "quest_smuggler_01";
	ch.model = "corsair2";
	ch.sex = "man";
	ch.sound_type = "pirate";
	LAi_NoRebirthEnable(ch);
	ch.nation = PIRATE;
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "none"
	ch.location.group = "goto";
	ch.location.locator = "goto4";
	ch.Dialog.Filename = "quest_smuggler_01_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "52";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "4";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "5";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetActorType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_NoRebirthEnable(ch);
	ch.greeting = "Gr_Quest_Smuggler_01";
	n = n + 1;

	makeref(ch,Characters[n]);		//  Fernam  Barrios -- korsar
	ch.name 	= "Фернам";
	ch.lastname = "Барьос";
	ch.id		= "Fernam  Barrios";
	ch.model	= "man1";
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.sound_type = "pirate";
	ch.location	= "none";
	ch.location.group = "goto";
	ch.location.locator = "goto28";
	ch.Dialog.Filename = "Evaristo Filho_dialog.c";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "0";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	ch.greeting = "Gr_Evaristo Filho";
	n = n + 1;

	makeref(ch,Characters[n]);		//  Leborio Violate -- korsar
	ch.name 	= "Леборио";
	ch.lastname = "Виолате";
	ch.id		= "Leborio Violate";
	ch.model	= "man2";
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.sound_type = "pirate";
	ch.location	= "none";
	ch.location.group = "goto";
	ch.location.locator = "goto29";
	ch.Dialog.Filename = "Evaristo Filho_dialog.c";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "0";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	ch.greeting = "Gr_Evaristo Filho";
	n = n + 1;

	makeref(ch,Characters[n]);		//  pirate for abordage 01
	ch.name 	= "Пират";
	ch.lastname = "";
	ch.id		= "pirate for abordage 01";
	ch.model	= "man2";
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.act.type = "soldier";
	ch.sound_type = "pirate";
	ch.location	= "none";
	ch.location.group = "goto";
	ch.location.locator = "goto1";
	ch.Dialog.Filename = "";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "0";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	n = n + 1;

	makeref(ch,Characters[n]);		//  pirate for abordage 02
	ch.name 	= "Пират";
	ch.lastname = "";
	ch.id		= "pirate for abordage 02";
	ch.model	= "man2";
	ch.sex = "man";
	LAi_NoRebirthEnable(ch);
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.sound_type = "pirate";
	ch.location	= "none";
	ch.location.group = "goto";
	ch.location.locator = "goto5";
	ch.Dialog.Filename = "";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "0";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	n = n + 1;

	makeref(ch,Characters[n]);		//  pirate for abordage 03
	ch.name 	= "Пират";
	ch.lastname = "";
	ch.id		= "pirate for abordage 03";
	ch.model	= "man2";
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.sound_type = "pirate";
	ch.location	= "none";
	ch.location.group = "goto";
	ch.location.locator = "goto4";
	ch.Dialog.Filename = "";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "0";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	n = n + 1;

	makeref(ch,Characters[n]);		//  pirate for quest muelle 01
	ch.name 	= "Пират";
	ch.lastname = "";
	ch.id		= "pirate for quest muelle 01";
	ch.model	= "man2";
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.sound_type = "pirate";
	ch.location	= "none";
	ch.location.group = "goto";
	ch.location.locator = "goto10";
	ch.Dialog.Filename = "";
	ch.nation = PIRATE;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "0";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	n = n + 1;

	makeref(ch,Characters[n]);		//  pirate for quest muelle 02
	ch.name 	= "Пират";
	ch.lastname = "";
	ch.id		= "pirate for quest muelle 02";
	ch.model	= "corsair1";
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.sound_type = "pirate";
	ch.location	= "none";
	ch.location.group = "goto";
	ch.location.locator = "goto10";
	ch.Dialog.Filename = "";
	ch.nation = PIRATE;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "0";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	n = n + 1;

	makeref(ch,Characters[n]);		//  pirate for quest muelle 03
	ch.name 	= "Пират";
	ch.lastname = "";
	ch.id		= "pirate for quest muelle 03";
	ch.model	= "korsar";
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.sound_type = "pirate";
	ch.location	= "none";
	ch.location.group = "goto";
	ch.location.locator = "goto10";
	ch.Dialog.Filename = "";
	ch.nation = PIRATE;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "0";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	n = n + 1;

	makeref(ch,Characters[n]);			// Pirate Captain 05
	ch.name 	= "Жиль";
	ch.lastname 	= "Дюбуа";
	ch.id		= "Pirate Captain 05";
	ch.model = "fisherman";
	ch.sex = "man";
	ch.act.type = "soldier";
	ch.sound_type = "pirate";
	LAi_NoRebirthEnable(ch);
	ch.nation = PIRATE;
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "none";//"Redmond"; //redmond_shore_01
	ch.location.group = "ships";
	ch.location.locator = "locator5";//locator8
	ch.Dialog.Filename = "Gyles Dubois_dialog.c";
	ch.Ship.Name = "Sirena";
	ch.Ship.Type = SHIP_BARQUE_ENGLAND;
	ch.Ship.Stopped = true;
	ch.Ship.Cannons.Type = CANNON_TYPE_CANNON_LBS16;
	ch.rank 	= 1;
	ch.reputation = "22";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "4";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "4";
	ch.skill.Cannons = "3";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	ch.greeting = "Gr_Gyles Dubois";
	n = n + 1;

	makeref(ch,Characters[n]);			// Pirate Captain 06
	ch.name 	= "Жиль";
	ch.lastname 	= "Дюбуа";
	ch.id		= "Pirate Captain 06";
	ch.model = "fisherman";
	ch.sex = "man";
	ch.act.type = "soldier";
	ch.sound_type = "pirate";
	LAi_NoRebirthEnable(ch);
	ch.nation = PIRATE;
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "none";
	ch.location.group = "quest_ships";
	ch.location.locator = "quest_ship9";
	ch.Dialog.Filename = "Gyles Dubois_dialog.c";
	ch.Ship.Name = "Sirena";
	ch.Ship.Type = SHIP_BARQUE_SPAIN;
	ch.Ship.Stopped = true;
	ch.Ship.Cannons.Type = CANNON_TYPE_CANNON_LBS16;
	ch.rank 	= 1;
	ch.reputation = "22";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "4";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "4";
	ch.skill.Cannons = "3";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	ch.greeting = "Gr_Gyles Dubois";
	n = n + 1;

	makeref(ch,Characters[n]);			// greenford citizen 01
	ch.name 	= "горожанин";
	ch.lastname 	= "";
	ch.id		= "greenford_citizen_01";
	ch.model = "TownGirl5";
	ch.sex = "woman";
	ch.act.type = "merchant";
	ch.sound_type = "female_citizen";
	LAi_NoRebirthEnable(ch);
	ch.nation = ENGLAND;
	ch.location	= "none";
	ch.location.group = "goto";
	ch.location.locator = "none";
	ch.Dialog.Filename = "greenford_citizen_01_dialog.c";
	ch.greeting = "Gr_greenford_citizen_01";
	ch.rank 	= 1;
	ch.reputation = "42";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "0";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "0";
	ch.skill.Cannons = "0";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetActorType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	n = n + 1;

	makeref(ch,Characters[n]);			// murderer_in_douwesen_01
	ch.name 	= "горожанин";
	ch.lastname 	= "";
	ch.id		= "murderer_in_douwesen_01";
	ch.model = "man1_1";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	LAi_NoRebirthEnable(ch);
	ch.nation = PIRATE;
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "none";
	ch.location.group = "goto";
	ch.location.locator = "none";
	ch.Dialog.Filename = "murderer_in_greenford_01_dialog.c";
	ch.greeting = "Gr_Murderer_in_Greenford_01";
	ch.rank 	= 1;
	ch.reputation = "19";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "2";
	ch.skill.Sailing = "0";
	ch.skill.Accuracy = "0";
	ch.skill.Cannons = "0";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetActorType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 40.0, 40.0);
	n = n + 1;

	makeref(ch,Characters[n]);			// murderer_in_douwesen_02
	ch.name 	= "горожанин";
	ch.lastname 	= "";
	ch.id		= "murderer_in_douwesen_02";
	ch.model = "corsair2";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	LAi_NoRebirthEnable(ch);
	ch.nation = PIRATE;
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "none";
	ch.location.group = "goto";
	ch.location.locator = "none";
	ch.Dialog.Filename = "murderer_in_greenford_01_dialog.c";
	ch.greeting = "Gr_Murderer_in_Greenford_01";
	ch.rank 	= 1;
	ch.reputation = "19";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "4";
	ch.skill.Sailing = "0";
	ch.skill.Accuracy = "0";
	ch.skill.Cannons = "0";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetActorType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 40.0, 40.0);
	n = n + 1;

	makeref(ch,Characters[n]);			// murderer_in_douwesen_03
	ch.name 	= "горожанин";
	ch.lastname 	= "";
	ch.id		= "murderer_in_douwesen_03";
	ch.model = "bocman";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	LAi_NoRebirthEnable(ch);
	ch.nation = PIRATE;
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "none";
	ch.location.group = "goto";
	ch.location.locator = "none";
	ch.Dialog.Filename = "murderer_in_greenford_01_dialog.c";
	ch.greeting = "Gr_Murderer_in_Greenford_01";
	ch.rank 	= 1;
	ch.reputation = "19";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "0";
	ch.skill.Accuracy = "0";
	ch.skill.Cannons = "0";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetActorType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 40.0, 40.0);
	n = n + 1;

	makeref(ch,Characters[n]);			// murderer_in_greenford_04
	ch.name 	= "горожанин";
	ch.lastname 	= "";
	ch.id		= "murderer_in_greenford_04";
	ch.model = "man1";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	LAi_NoRebirthEnable(ch);
	ch.nation = ENGLAND;
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "none";
	ch.location.group = "goto";
	ch.location.locator = "none";
	ch.Dialog.Filename = "murderer_in_greenford_01_dialog.c";
	ch.greeting = "Gr_Murderer_in_Greenford_01";
	ch.rank 	= 1;
	ch.reputation = "42";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "0";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "0";
	ch.skill.Cannons = "0";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetActorType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 40.0, 40.0);
	n = n + 1;

	makeref(ch,Characters[n]);			// murderer_in_greenford_05
	ch.name 	= "горожанин";
	ch.lastname 	= "";
	ch.id		= "murderer_in_greenford_05";
	ch.model = "man2";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	LAi_NoRebirthEnable(ch);
	ch.nation = ENGLAND;
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "none";
	ch.location.group = "goto";
	ch.location.locator = "none";
	ch.Dialog.Filename = "murderer_in_greenford_01_dialog.c";
	ch.greeting = "Gr_Murderer_in_Greenford_01";
	ch.rank 	= 1;
	ch.reputation = "42";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "0";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "0";
	ch.skill.Cannons = "0";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 40.0, 40.0);
	n = n + 1;

	makeref(ch,Characters[n]);			// murderer_in_greenford_06
	ch.name 	= "горожанин";
	ch.lastname 	= "";
	ch.id		= "murderer_in_greenford_06";
	ch.model = "man3";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	LAi_NoRebirthEnable(ch);
	ch.nation = ENGLAND;
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "none";
	ch.location.group = "goto";
	ch.location.locator = "none";
	ch.Dialog.Filename = "murderer_in_greenford_01_dialog.c";
	ch.greeting = "Gr_Murderer_in_Greenford_01";
	ch.rank 	= 1;
	ch.reputation = "42";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "0";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "0";
	ch.skill.Cannons = "0";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetActorType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 40.0, 40.0);
	n = n + 1;

	makeref(ch,Characters[n]);			// Eng Soldier for residence
	ch.name 	= "Солдат";
	ch.lastname 	= "";
	ch.id		= "Eng Soldier for residence 01";
	ch.model = "soldier_eng";
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_NoRebirthEnable(ch);
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "none"
	ch.location.group = "Quest_ships";
	ch.location.locator = "quest_ship_7";
	ch.Dialog.Filename = "falaise de fleur soldier_dialog.c";
	ch.nation = ENGLAND;
	ch.rank 	= 1;
	ch.reputation = "52";
	ch.experience = "0";
	ch.skill.Leadership = "4";
	ch.skill.Fencing = "6";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "5";
	ch.skill.Cannons = "3";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	ch.greeting = "Gr_falaise de fleur soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			// Eng Soldier for residence
	ch.name 	= "Солдат";
	ch.lastname 	= "";
	ch.id		= "Eng Soldier for residence 02";
	ch.model = "soldier_eng";
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_NoRebirthEnable(ch);
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "none"
	ch.location.group = "Quest_ships";
	ch.location.locator = "quest_ship_7";
	ch.Dialog.Filename = "falaise de fleur soldier_dialog.c";
	ch.nation = ENGLAND;
	ch.rank 	= 1;
	ch.reputation = "52";
	ch.experience = "0";
	ch.skill.Leadership = "4";
	ch.skill.Fencing = "6";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "5";
	ch.skill.Cannons = "3";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	ch.greeting = "Gr_falaise de fleur soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			// peasant
	ch.name 	= "горожанин";
	ch.lastname 	= "";
	ch.id		= "peasant";
	ch.model = "man5";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	LAi_NoRebirthEnable(ch);
	ch.nation = HOLLAND;
	ch.location	= "none";
	ch.location.group = "goto";
	ch.location.locator = "none";
	ch.Dialog.Filename = "peasant_dialog.c";
	ch.greeting = "Gr_Peasant";
	ch.rank 	= 1;
	ch.reputation = "42";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "0";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "0";
	ch.skill.Cannons = "0";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetActorType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	n = n + 1;

	makeref(ch,Characters[n]);			// Redmond Soldier for drink fight
	ch.name 	= "Солдат";
	ch.lastname 	= "";
	ch.id		= "Redmond Soldier";
	ch.model = "soldier_eng";
	ch.sex = "man";
	ch.sound_type = "soldier";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "none"
	ch.location.group = "none";
	ch.location.locator = "none";
	ch.Dialog.Filename = "Redmond soldier_dialog.c";
	ch.nation = ENGLAND;
	ch.rank 	= 1;
	ch.reputation = "52";
	ch.experience = "0";
	ch.skill.Leadership = "4";
	ch.skill.Fencing = "6";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "5";
	ch.skill.Cannons = "3";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	ch.greeting = "Gr_Redmond Soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			// Greenford Soldier for drink fight
	ch.name 	= "Солдат";
	ch.lastname 	= "";
	ch.id		= "Greenford Soldier";
	ch.model = "soldier_eng";
	ch.sex = "man";
	ch.sound_type = "soldier";;
	LAi_NoRebirthEnable(ch);
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "none"
	ch.location.group = "none";
	ch.location.locator = "none";
	ch.Dialog.Filename = "Greenford soldier_dialog.c";
	ch.nation = ENGLAND;
	ch.rank 	= 1;
	ch.reputation = "52";
	ch.experience = "0";
	ch.skill.Leadership = "4";
	ch.skill.Fencing = "6";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "5";
	ch.skill.Cannons = "3";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	n = n + 1;

	makeref(ch,Characters[n]);			// Oxbay Soldier for drink fight
	ch.name 	= "Солдат";
	ch.lastname 	= "";
	ch.id		= "Oxbay Soldier";
	ch.model = "soldier_eng";
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_NoRebirthEnable(ch);
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "none"
	ch.location.group = "none";
	ch.location.locator = "none";
	ch.Dialog.Filename = "Oxbay soldier_dialog.c";
	ch.nation = ENGLAND;
	ch.rank 	= 1;
	ch.reputation = "52";
	ch.experience = "0";
	ch.skill.Leadership = "4";
	ch.skill.Fencing = "6";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "5";
	ch.skill.Cannons = "3";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	ch.greeting = "Gr_Oxbay Soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			// Douwesen Soldier for drink fight
	ch.name 	= "Солдат";
	ch.lastname 	= "";
	ch.id		= "Douwesen Soldier";
	ch.model = "soldier_hol";
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_NoRebirthEnable(ch);
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "none"
	ch.location.group = "none";
	ch.location.locator = "none";
	ch.Dialog.Filename = "Douwesen soldier_dialog.c";
	ch.nation = HOLLAND;
	ch.rank 	= 1;
	ch.reputation = "52";
	ch.experience = "0";
	ch.skill.Leadership = "4";
	ch.skill.Fencing = "6";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "5";
	ch.skill.Cannons = "3";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	ch.greeting = "Gr_Douwesen Soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			// MUELLE Soldier for drink fight
	ch.name 	= "Солдат";
	ch.lastname 	= "";
	ch.id		= "Muelle Soldier";
	ch.model = "soldier_spa";
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_NoRebirthEnable(ch);
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "none"
	ch.location.group = "none";
	ch.location.locator = "none";
	ch.Dialog.Filename = "Isla Muelle soldier_dialog.c";
	ch.nation = SPAIN;
	ch.rank 	= 1;
	ch.reputation = "52";
	ch.experience = "0";
	ch.skill.Leadership = "4";
	ch.skill.Fencing = "6";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "5";
	ch.skill.Cannons = "3";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	ch.greeting = "Gr_isla muelle soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			// Conceicao Soldier for drink fight
	ch.name 	= "Солдат";
	ch.lastname 	= "";
	ch.id		= "Conceicao Soldier";
	ch.model = "soldier_por";
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_NoRebirthEnable(ch);
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "none"
	ch.location.group = "none";
	ch.location.locator = "none";
	ch.Dialog.Filename = "Conceicao soldier_dialog.c";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "52";
	ch.experience = "0";
	ch.skill.Leadership = "4";
	ch.skill.Fencing = "6";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "5";
	ch.skill.Cannons = "3";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	ch.greeting = "Gr_Conceicao Soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			// QC Soldier for drink fight
	ch.name 	= "Пират";
	ch.lastname 	= "";
	ch.id		= "QC Soldier";
	ch.model = "corsair2";
	ch.sex = "man";
	ch.sound_type = "pirate";
	LAi_NoRebirthEnable(ch);
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "none"
	ch.location.group = "none";
	ch.location.locator = "none";
	ch.Dialog.Filename = "QC soldier_dialog.c";
	ch.nation = PIRATE;
	ch.rank 	= 1;
	ch.reputation = "52";
	ch.experience = "0";
	ch.skill.Leadership = "4";
	ch.skill.Fencing = "6";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "5";
	ch.skill.Cannons = "3";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	n = n + 1;

	makeref(ch,Characters[n]);			// Smugglers Soldier for drink fight
	ch.name 	= "Солдат";
	ch.lastname 	= "";
	ch.id		= "Smugglers Soldier";
	ch.model = "korsar";
	ch.sex = "man";
	ch.sound_type = "pirate";
	LAi_NoRebirthEnable(ch);
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "none"
	ch.location.group = "none";
	ch.location.locator = "none";
	ch.Dialog.Filename = "Smugglers soldier_dialog.c";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "52";
	ch.experience = "0";
	ch.skill.Leadership = "4";
	ch.skill.Fencing = "6";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "5";
	ch.skill.Cannons = "3";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	n = n + 1;

	makeref(ch,Characters[n]);			// Pirate Soldier for drink fight
	ch.name 	= "Солдат";
	ch.lastname 	= "";
	ch.id		= "Pirate Soldier";
	ch.model = "man1";
	ch.sex = "man";
	ch.sound_type = "pirate";
	LAi_NoRebirthEnable(ch);
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "none"
	ch.location.group = "none";
	ch.location.locator = "none";
	ch.Dialog.Filename = "Pirate soldier_dialog.c";
	ch.nation = PIRATE;
	ch.rank 	= 1;
	ch.reputation = "52";
	ch.experience = "0";
	ch.skill.Leadership = "4";
	ch.skill.Fencing = "6";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "5";
	ch.skill.Cannons = "3";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	n = n + 1;

	makeref(ch,Characters[n]);			// Falaise De Fleur Soldier for drink fight
	ch.name 	= "Солдат";
	ch.lastname 	= "";
	ch.id		= "Falaise De Fleur Soldier";
	ch.model = "soldier_fra";
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_NoRebirthEnable(ch);
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "none"
	ch.location.group = "none";
	ch.location.locator = "none";
	ch.Dialog.Filename = "Falaise de Fleur soldier_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "52";
	ch.experience = "0";
	ch.skill.Leadership = "4";
	ch.skill.Fencing = "6";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "5";
	ch.skill.Cannons = "3";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	ch.greeting = "Gr_falaise de fleur soldier";
	n = n + 1;

	makeref(ch,Characters[n]);		// Rian Dekkers -- towngirl1
	ch.name 	= "Риан";
	ch.lastname = "Деккерс";
	ch.id		= "Rian Dekkers";
	ch.model	= "towngirl1";
	ch.sex = "woman";
	LAi_NoRebirthEnable(ch);
	ch.sound_type = "female_citizen";
	ch.location	= "Douwesen_town";
	ch.location.group = "merchant";
	ch.location.locator = "merchant1";
	ch.Dialog.Filename = "Unhappy women_dialog.c";
	ch.greeting = "Gr_Unhappy women";
	ch.nation = HOLLAND;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetMerchantType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	n = n + 1;

	makeref(ch,Characters[n]);		// Janneke Blinkerhof -- towngirl1
	ch.name 	= "Жаннеке";
	ch.lastname = "Блинкерхоф";
	ch.id		= "Janneke Blinkerhof";
	ch.model	= "towngirl2";
	ch.sex = "woman";
	LAi_NoRebirthEnable(ch);
	ch.sound_type = "female_citizen";
	ch.location	= "Douwesen_town";
	ch.location.group = "merchant";
	ch.location.locator = "merchant2";
	ch.Dialog.Filename = "Unhappy women_dialog.c";
	ch.greeting = "Gr_Unhappy women";
	ch.nation = HOLLAND;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetMerchantType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	n = n + 1;

	makeref(ch,Characters[n]);		// Lisebet Schefold -- towngirl1
	ch.name 	= "Лизебет";
	ch.lastname = "Шефольд";
	ch.id		= "Lisebet Schefold";
	ch.model	= "towngirl3";
	ch.sex = "woman";
	LAi_NoRebirthEnable(ch);
	ch.sound_type = "female_citizen";
	ch.location	= "Douwesen_town";
	ch.location.group = "merchant";
	ch.location.locator = "merchant3";
	ch.Dialog.Filename = "Unhappy women_dialog.c";
	ch.greeting = "Gr_Unhappy women";
	ch.nation = HOLLAND;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetMerchantType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	n = n + 1;

	makeref(ch,Characters[n]);		// Gheraed Drabbe -- man3
	ch.name 	= "Геред";
	ch.lastname = "Драббе";
	ch.id		= "Gheraed Drabbe";
	ch.model	= "man3";
	ch.sex = "man";
	LAi_NoRebirthEnable(ch);
	ch.sound_type = "male_citizen";
	ch.location	= "none";
	ch.location.group = "sit";
	ch.location.locator = "sit5";
	ch.Dialog.Filename = "Gheraed Drabbe_dialog.c";
	ch.nation = HOLLAND;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetSitType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	ch.greeting = "Gr_Gheraed Drabbe";
	n = n + 1;

	makeref(ch,Characters[n]);		// Balltesar Figueiredo -- man3
	ch.name 	= "Баллтезар";
	ch.lastname = "Фигуейредо";
	ch.id		= "Balltesar Figueiredo";
	ch.model	= "man2";
	ch.sex = "man";
	LAi_NoRebirthEnable(ch);
	ch.sound_type = "male_citizen";
	ch.location	= "none";
	ch.location.group = "sit";
	ch.location.locator = "sit7";
	ch.Dialog.Filename = "Balltesar Figueiredo_dialog.c";
	ch.nation = HOLLAND;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetSitType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	ch.greeting = "Gr_Balltesar Figueiredo";
	n = n + 1;

	makeref(ch,Characters[n]);		// father Gareth -- man3
	ch.name 	= "отец";
	ch.lastname = "Гарет";
	ch.id		= "father Gareth";
	ch.model	= "monk2";
	ch.sex = "man";
	LAi_NoRebirthEnable(ch);
	ch.sound_type = "priest";
	ch.location	= "none";
	ch.location.group = "goto";
	ch.location.locator = "goto13";
	ch.Dialog.Filename = "father Gareth_dialog.c";
	ch.nation = ENGLAND;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetMerchantType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_NoRebirthEnable(ch);
	ch.greeting = "Gr_father Gareth";
	n = n + 1;

	makeref(ch,Characters[n]);			// 
	ch.name 	= "Загадочный человек";
	ch.lastname 	= "";
	ch.id		= "Mystery_Man_01";
	ch.model = "ANIMISTS2";
	ch.sex = "man";
	ch.sound_type = "priest";
	ch.act.escape = 0;
	ch.activity_begin = "0";
	ch.activity_end = "24";
	LAi_NoRebirthEnable(ch);
	ch.nation = PIRATE;
	GiveItem2Character(ch, "blade5");
	ch.equip.blade = "blade5";
	ch.location	= "none";//"Redmond"; //redmond_shore_01
	ch.location.group = "";
	ch.location.locator = "";//locator8
	ch.Dialog.Filename = "Quest_ANIMISTS_dialog.c";
	ch.greeting = "Gr_Quest_ANIMISTS";
	ch.Ship.Name = "Unnamed";
	ch.Ship.Type = SHIP_BARQUE2_ENGLAND;
	ch.Ship.Stopped = true;
	ch.Ship.Cannons.Type = CANNON_TYPE_CANNON_LBS24;
	ch.rank 	= 1;
	ch.reputation = "22";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "4";
	ch.skill.Sailing = "5";
	ch.skill.Accuracy = "4";
	ch.skill.Cannons = "6";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "2";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetActorType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_NoRebirthEnable(ch);
	n = n + 1;

	makeref(ch,Characters[n]);			// 
	ch.name 	= "Загадочный человек";
	ch.lastname 	= "";
	ch.id		= "Mystery_Man_02";
	ch.model = "ANIMISTS2";
	ch.sex = "man";
	ch.sound_type = "priest";
	ch.act.escape = 0;
	LAi_NoRebirthEnable(ch);
	ch.nation = PIRATE;
	GiveItem2Character(ch, "blade5");
	ch.equip.blade = "blade5";
	ch.location	= "none";//"Redmond"; //redmond_shore_01
	ch.location.group = "";
	ch.location.locator = "";//locator8
	ch.Dialog.Filename = "Quest_ANIMISTS_dialog.c";
	ch.greeting = "Gr_Quest_ANIMISTS";
	ch.Ship.Name = "Unnamed";
	ch.Ship.Type = SHIP_BRIG2_ENGLAND;
	ch.Ship.Stopped = true;
	ch.Ship.Cannons.Type = CANNON_TYPE_CANNON_LBS24;
	ch.rank 	= 1;
	ch.reputation = "22";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "4";
	ch.skill.Sailing = "5";
	ch.skill.Accuracy = "4";
	ch.skill.Cannons = "6";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "2";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetActorType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_NoRebirthEnable(ch);
	n = n + 1;

	makeref(ch,Characters[n]);			// 
	ch.name 	= "Загадочный человек";
	ch.lastname 	= "";
	ch.id		= "Mystery_Man_03";
	ch.model = "ANIMISTS2";
	ch.sex = "man";
	ch.sound_type = "priest";
	ch.act.escape = 0;
	LAi_NoRebirthEnable(ch);
	ch.nation = PIRATE;
	GiveItem2Character(ch, "blade5");
	ch.equip.blade = "blade5";
	ch.location	= "none";//"Redmond"; //redmond_shore_01
	ch.location.group = "";
	ch.location.locator = "";//locator8
	ch.Dialog.Filename = "Quest_ANIMISTS_dialog.c";
	ch.greeting = "Gr_Quest_ANIMISTS";
	ch.Ship.Name = "Unnamed";
	ch.Ship.Type = SHIP_GALEOTH2_ENGLAND;
	ch.Ship.Stopped = true;
	ch.Ship.Cannons.Type = CANNON_TYPE_CANNON_LBS24;
	ch.rank 	= 1;
	ch.reputation = "22";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "4";
	ch.skill.Sailing = "5";
	ch.skill.Accuracy = "4";
	ch.skill.Cannons = "6";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "2";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetActorType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_NoRebirthEnable(ch);
	n = n + 1;


//Контрабандисты для перевозки контрабанды


	makeref(ch,Characters[n]);			// контрабандист 1
	ch.name 	= "Контрабандист";
	ch.lastname 	= "";
	ch.id		= "Rand_Smug01";
//	ch.model = "sat_monk";
	ch.sex = "man";
	ch.sound_type = "pirate";
//	ch.act.escape = 0;
	ch.act.rebirth = 1;
	ch.nation = PIRATE;
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "none";//"Redmond"; //redmond_shore_01
	ch.location.group = "";
	ch.location.locator = "";//locator8
	ch.Dialog.Filename = "Smuggler_OnShore_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "22";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "4";
	ch.skill.Sailing = "5";
	ch.skill.Accuracy = "4";
	ch.skill.Cannons = "6";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "2";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	ch.greeting = "Gr_Smuggler_OnShore";
	n = n + 1;

	makeref(ch,Characters[n]);			// контрабандист 2
	ch.name 	= "Контрабандист";
	ch.lastname 	= "";
	ch.id		= "Rand_Smug02";
//	ch.model = "sat_monk";
	ch.sex = "man";
	ch.sound_type = "pirate";
//	ch.act.escape = 0;
	ch.act.rebirth = 1;
	ch.nation = PIRATE;
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "none";//"Redmond"; //redmond_shore_01
	ch.location.group = "";
	ch.location.locator = "";//locator8
	ch.Dialog.Filename = "Smuggler_OnShore_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "22";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "4";
	ch.skill.Sailing = "5";
	ch.skill.Accuracy = "4";
	ch.skill.Cannons = "6";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "2";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	ch.greeting = "Gr_Smuggler_OnShore";
	n = n + 1;

	makeref(ch,Characters[n]);			// контрабандист 3
	ch.name 	= "Контрабандист";
	ch.lastname 	= "";
	ch.id		= "Rand_Smug03";
//	ch.model = "sat_monk";
	ch.sex = "man";
	ch.sound_type = "pirate";
//	ch.act.escape = 0;
	ch.act.rebirth = 1;
	ch.nation = PIRATE;
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "none";//"Redmond"; //redmond_shore_01
	ch.location.group = "";
	ch.location.locator = "";//locator8
	ch.Dialog.Filename = "Smuggler_OnShore_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "22";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "4";
	ch.skill.Sailing = "5";
	ch.skill.Accuracy = "4";
	ch.skill.Cannons = "6";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "2";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	ch.greeting = "Gr_Smuggler_OnShore";
	n = n + 1;

	makeref(ch,Characters[n]);			// Bernardo Gamboa - испанец. корсар на службе голландии
	ch.name 	= "Бернардо";
	ch.lastname 	= "Гамбоа";
	ch.id		= "Bernardo Gamboa";
	ch.model = "corsair2";
	ch.sex = "man";
	ch.sound_type = "pirate";
	LAi_NoRebirthEnable(ch);
	ch.nation = PIRATE;
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.Dialog.Filename = "Bernardo Gamboa_dialog.c";
	ch.location	= "Gamboa_ship";
	ch.location.group = "goto";
	ch.location.locator = "goto4";
	ch.Ship.Name = "Neptunus";
	ch.Ship.Type = SHIP_CORVETTE_SPAIN;
	ch.Ship.Stopped = true;
	ch.Ship.Cannons.Type = CANNON_TYPE_CANNON_LBS24;
	ch.rank 	= 1;
	ch.reputation = "22";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "7";
	ch.skill.Sailing = "5";
	ch.skill.Accuracy = "4";
	ch.skill.Cannons = "6";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "2";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.perks.list.BasicDefense = true;
	ch.perks.list.AdvancedDefense = true;
	ch.perks.list.SwordplayProfessional = true;
	ch.money = "10";
	LAi_SetStayType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	ch.greeting = "Gr_Bernardo Gamboa";
	n = n + 1;

	makeref(ch,Characters[n]);			// Corentin Lucay - помощник пердыдущего перса
	ch.name 	= "Корентин";
	ch.lastname 	= "Люкай";
	ch.id		= "Corentin Lucay";
	ch.model = "corsair1_1";
	ch.sex = "man";
	ch.sound_type = "pirate";
	LAi_NoRebirthEnable(ch);
	ch.nation = PIRATE;
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.Dialog.Filename = "Corentin Lucay_dialog.c";
	ch.greeting = "Gr_Corentin Lucay";
	ch.location	= "Gamboa_ship";
	ch.location.group = "goto";
	ch.location.locator = "goto3";
	ch.rank 	= 1;
	ch.reputation = "26";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "2";
	ch.skill.Accuracy = "3";
	ch.skill.Cannons = "3";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "2";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetStayType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	n = n + 1;

	makeref(ch,Characters[n]);		//первый капитан береговой стражи
	ch.name 	= " ";
	ch.lastname = " ";
	ch.id		= "Coastal_Captain01";
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "None";
	ch.location.group = "";
	ch.location.locator = "";
//	ch.Dialog.Filename = "blaze_dialog.c";
	ch.reputation = "50";
	ch.experience = 0;//CalculateExperienceFromRank(sti(ch.rank));
	ch.Ship.Name = "Dolphine";
	//ch.Ship.Type = SHIP_FRIGATE_ENGLAND;
	ch.Ship.Type = SHIP_LUGGER_ENGLAND;
	ch.Ship.Cannons.Type = CANNON_TYPE_CANNON_LBS24;
	ch.ship.cargo.goods.bombs = 1000;
	ch.Ship.Stopped = true;
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	n = n + 1;

	makeref(ch,Characters[n]);		//второй капитан береговой стражи
	ch.name 	= " ";
	ch.lastname = " ";
	ch.id		= "Coastal_Captain02";
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "None";
	ch.location.group = "";
	ch.location.locator = "";
//	ch.Dialog.Filename = "blaze_dialog.c";
	ch.reputation = "50";
	ch.experience = 0;//CalculateExperienceFromRank(sti(ch.rank));
	ch.Ship.Name = "Dolphine";
	//ch.Ship.Type = SHIP_FRIGATE_ENGLAND;
	ch.Ship.Type = SHIP_LUGGER_ENGLAND;
	ch.Ship.Cannons.Type = CANNON_TYPE_CANNON_LBS24;
	ch.ship.cargo.goods.bombs = 1000;
	ch.Ship.Stopped = true;
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	n = n + 1;


	makeref(ch,Characters[n]);		//третий капитан береговой стражи
	ch.name 	= " ";
	ch.lastname = " ";
	ch.id		= "Coastal_Captain03";
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "None";
	ch.location.group = "";
	ch.location.locator = "";
//	ch.Dialog.Filename = "blaze_dialog.c";
	ch.reputation = "50";
	ch.experience = 0;//CalculateExperienceFromRank(sti(ch.rank));
	ch.Ship.Name = "Dolphine";
	//ch.Ship.Type = SHIP_FRIGATE_ENGLAND;
	ch.Ship.Type = SHIP_LUGGER_ENGLAND;
	ch.Ship.Cannons.Type = CANNON_TYPE_CANNON_LBS24;
	ch.ship.cargo.goods.bombs = 1000;
	ch.Ship.Stopped = true;
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	n = n + 1;

	makeref(ch,Characters[n]);			// Mergildo Hurtado - капитан барка со священниками
	ch.name 	= "Мергильдо";
	ch.lastname 	= "Хуртадо";
	ch.id		= "Mergildo Hurtado";
	ch.model = "offic_spa";
	ch.sex = "man";
	ch.sound_type = "seaman";
	LAi_NoRebirthEnable(ch);
	ch.Ship.AI.GroupName = "saints";
	ch.Ship.AI.Task = "attack";
	ch.nation = SPAIN;
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "none";
	ch.location.group = "";
	ch.location.locator = "";
	ch.Dialog.Filename = "Mergildo Hurtado_dialog.c";
	ch.Ship.Name = "Montanez";
	ch.Ship.Type = SHIP_BARQUE_SPAIN;
	ch.Ship.Stopped = true;
	ch.Ship.Cannons.Type = CANNON_TYPE_CANNON_LBS24;
	ch.rank 	= 1;
	ch.reputation = "22";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "4";
	ch.skill.Accuracy = "2";
	ch.skill.Cannons = "3";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "2";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetActorType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	ch.greeting = "Gr_Mergildo Hurtado";
	n = n + 1;

	makeref(ch,Characters[n]);			// Jordano - сын кузнеца на Муэле
	ch.name 	= "Джордано";
	ch.lastname 	= "";
	ch.id		= "Jordano";
	ch.model = "man4";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	LAi_NoRebirthEnable(ch);
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "none"; //redmond_shore_01
	ch.location.group = "goto";
	ch.location.locator = "none";//locator8
	ch.Dialog.Filename = "Jordano_dialog.c";
	ch.greeting = "Gr_Jordano";
	ch.rank 	= 1;
	ch.reputation = "22";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetActorType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	n = n + 1;


// Nigel Blythe  quest

	makeref(ch,Characters[n]);		// Friedrich Maxwell
	ch.name 	= "Фридрих";
	ch.lastname = "Максвел";
	ch.id		= "Friedrich Maxwell";
	ch.model	= "corsair3";
	ch.sex = "man";
	ch.location	= "none";
	ch.location.group = "sit";
	ch.location.locator = "sit2";
	ch.Dialog.Filename = "";
	ch.nation = PIRATE;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetSitType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	ch.greeting = "Gr_Maxwell";
	n = n + 1;

	makeref(ch,Characters[n]);		// Luis Meranda
	ch.name 	= "Луис";
	ch.lastname = "Меранда";
	ch.id		= "Luis Meranda";
	ch.model	= "man1";
	ch.sex = "man";
	ch.location	= "none";
	ch.location.group = "sit";
	ch.location.locator = "sit2";
	ch.Dialog.Filename = "Luis Meranda_dialog.c";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetSitType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	n = n + 1;

	makeref(ch,Characters[n]);		// Pirates_7 --
	ch.name 	= "Пират";
	ch.lastname = "семь";
	ch.id		= "Pirates_7";
	ch.model	= "man4";
	ch.sex = "man";
	GiveItem2Character(ch, GUN_COMMON);
	ch.equip.gun = GUN_COMMON;
	GiveItem2Character(ch, BLADE_LONG);
	ch.equip.blade = BLADE_LONG;
	ch.location	= "None";
	ch.location.group = "sit";
	ch.location.locator = "sit3";
	ch.Dialog.Filename = "Habitue_dialog.c";
	ch.nation = PIRATE;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "0";
	ch.Ship.Name = "Duk";
	ch.Ship.Type = SHIP_BRIG_FRANCE;
	ch.Ship.Stopped = true;
	ch.Ship.Cannons.Type = CANNON_TYPE_CANNON_LBS12;
	LAi_SetSitType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	n = n + 1;

	makeref(ch,Characters[n]);			// Claudio Murena.
	ch.name 	= "Клаудио";
	ch.lastname 	= "Мурена";
	ch.id		= "Claudio Murena";
	ch.model = "man2";
	ch.sex = "man";
	ch.location	= "None";
	ch.location.group = "sit";
	ch.location.locator = "sit2";
	ch.Dialog.Filename = "";
	ch.greeting = "Gr_Murena";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetSitType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	n = n + 1;


// Nigel Blythe quest

	//Hitman

	makeref(ch,Characters[n]);			// Ambroz Bricenos
	ch.name 	= "Амброз";
	ch.lastname 	= "Бриценос";
	ch.id		= "Ambroz Bricenos";
	ch.model = "Man3_1";
	ch.sex = "man";
	ch.sound_type = "pirate";
	GiveItem2Character(ch, BLADE_LONG);
	ch.equip.blade = BLADE_LONG;
	ch.location	= "none";
	ch.location.group = "";
	ch.location.locator = "";
	ch.Dialog.Filename = "Ambroz Bricenos_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "10";
	ch.experience = "0";
	ch.skill.Leadership = "0";
	ch.skill.Fencing = "2";
	ch.skill.Sailing = "0";
	ch.skill.Accuracy = "0";
	ch.skill.Cannons = "0";
	ch.skill.Grappling = "0";
	ch.skill.Repair = "0";
	ch.skill.Defence = "0";
	ch.skill.Commerce = "3";
	ch.skill.Sneak = "0";
	ch.money = "100";
	ch.quest.meeting = "0";
	LAi_SetStayType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 50.0, 50.0);
	ch.greeting = "Gr_Ambroz Bricenos";
	n = n + 1;

	makeref(ch,Characters[n]);			// Mateus Santos
	ch.name 	= "Матеус";
	ch.lastname 	= "Сантос";
	ch.id		= "Mateus Santos";
	ch.model = "blackman";
	ch.sex = "man";
	ch.sound_type = "pirate";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	GiveItem2Character(ch, GUN_COMMON);
	ch.equip.gun = GUN_COMMON;
	ch.location	= "none";
	ch.location.group = "";
	ch.location.locator = "";
	ch.Dialog.Filename = "Mateus Santos_dialog.c";
	ch.greeting = "Gr_Mateus Santos";
	ch.rank 	= 5;
	ch.reputation = "50";
	ch.experience = "0";
	ch.skill.Leadership = "6";
	ch.skill.Fencing = "7";
	ch.skill.Sailing = "0";
	ch.skill.Accuracy = "0";
	ch.skill.Cannons = "0";
	ch.skill.Grappling = "0";
	ch.skill.Repair = "0";
	ch.skill.Defence = "0";
	ch.skill.Commerce = "4";
	ch.skill.Sneak = "0";
	ch.money = "5000";
	ch.quest.meeting = "0";
	LAi_SetStayType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 140.0, 140.0);
	n = n + 1;

	makeref(ch,Characters[n]);			// Thug 1
	ch.name 	= "Вор";
	ch.lastname 	= "";
	ch.id		= "Thug1";
	ch.model = "pirat6";
	ch.sex = "man";
	ch.sound_type = "pirate";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	GiveItem2Character(ch, GUN_COMMON);
	ch.equip.gun = GUN_COMMON;
	ch.location	= "none";
	ch.location.group = "";
	ch.location.locator = "";
	ch.Dialog.Filename = "Thug_dialog.c";
	ch.greeting = "Gr_Thug";
	ch.rank 	= 3;
	ch.reputation = "20";
	ch.experience = "0";
	ch.skill.Leadership = "2";
	ch.skill.Fencing = "5";
	ch.skill.Sailing = "0";
	ch.skill.Accuracy = "0";
	ch.skill.Cannons = "0";
	ch.skill.Grappling = "0";
	ch.skill.Repair = "0";
	ch.skill.Defence = "0";
	ch.skill.Commerce = "2";
	ch.skill.Sneak = "0";
	ch.money = "200";
	ch.quest.meeting = "0";
	LAi_SetStayType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 100.0, 100.0);
	n = n + 1;

	makeref(ch,Characters[n]);			// Thug 2
	ch.name 	= "Вор";
	ch.lastname 	= "";
	ch.id		= "Thug2";
	ch.model = "pirat7";
	ch.sex = "man";
	ch.sound_type = "pirate";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	GiveItem2Character(ch, GUN_COMMON);
	ch.equip.gun = GUN_COMMON;
	ch.location	= "none";
	ch.location.group = "";
	ch.location.locator = "";
	ch.Dialog.Filename = "Thug_dialog.c";
	ch.greeting = "Gr_Thug";
	ch.rank 	= 3;
	ch.reputation = "20";
	ch.experience = "0";
	ch.skill.Leadership = "2";
	ch.skill.Fencing = "5";
	ch.skill.Sailing = "0";
	ch.skill.Accuracy = "0";
	ch.skill.Cannons = "0";
	ch.skill.Grappling = "0";
	ch.skill.Repair = "0";
	ch.skill.Defence = "0";
	ch.skill.Commerce = "2";
	ch.skill.Sneak = "0";
	ch.money = "200";
	ch.quest.meeting = "0";
	LAi_SetStayType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 100.0, 100.0);
	n = n + 1;

	makeref(ch,Characters[n]);			// Thug 3
	ch.name 	= "Вор";
	ch.lastname 	= "";
	ch.id		= "Thug3";
	ch.model = "pirat8";
	ch.sex = "man";
	ch.sound_type = "pirate";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	GiveItem2Character(ch, GUN_COMMON);
	ch.equip.gun = GUN_COMMON;
	ch.location	= "none";
	ch.location.group = "";
	ch.location.locator = "";
	ch.Dialog.Filename = "Thug_dialog.c";
	ch.greeting = "Gr_Thug";
	ch.rank 	= 3;
	ch.reputation = "20";
	ch.experience = "0";
	ch.skill.Leadership = "2";
	ch.skill.Fencing = "5";
	ch.skill.Sailing = "0";
	ch.skill.Accuracy = "0";
	ch.skill.Cannons = "0";
	ch.skill.Grappling = "0";
	ch.skill.Repair = "0";
	ch.skill.Defence = "0";
	ch.skill.Commerce = "2";
	ch.skill.Sneak = "0";
	ch.money = "200";
	ch.quest.meeting = "0";
	LAi_SetStayType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 100.0, 100.0);
	n = n + 1;

	makeref(ch,Characters[n]);			// Geffrey Bampfylde
	ch.name 	= "Джефри";
	ch.lastname 	= "Бампфилд";
	ch.id		= "Geffrey Bampfylde";
	ch.model = "fatman2";
	ch.sex = "man";
	ch.sound_type = "pirate";
	ch.location	= "none";
	ch.location.group = "";
	ch.location.locator = "";
	ch.Dialog.Filename = "Geffrey Bampfylde_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "50";
	ch.experience = "0";
	ch.skill.Leadership = "0";
	ch.skill.Fencing = "0";
	ch.skill.Sailing = "0";
	ch.skill.Accuracy = "0";
	ch.skill.Cannons = "0";
	ch.skill.Grappling = "0";
	ch.skill.Repair = "0";
	ch.skill.Defence = "0";
	ch.skill.Commerce = "6";
	ch.skill.Sneak = "0";
	ch.money = "1000";
	ch.quest.meeting = "0";
	LAi_SetStayType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 30.0, 30.0);
	ch.greeting = "Gr_Geffrey Bampfylde";
	n = n + 1;

	makeref(ch,Characters[n]);			// Bucho
	ch.name 	= "Бучо";
	ch.lastname 	= "";
	ch.id		= "Bucho";
	ch.model = "man4";
	ch.sex = "man";
	ch.sound_type = "pirate";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "none";
	ch.location.group = "";
	ch.location.locator = "";
	ch.Dialog.Filename = "Bucho_dialog.c";
	//ch.greeting = "Gr_Bucho";
	ch.rank 	= 2;
	ch.reputation = "20";
	ch.experience = "0";
	ch.skill.Leadership = "0";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "0";
	ch.skill.Accuracy = "0";
	ch.skill.Cannons = "0";
	ch.skill.Grappling = "0";
	ch.skill.Repair = "0";
	ch.skill.Defence = "0";
	ch.skill.Commerce = "0";
	ch.skill.Sneak = "0";
	ch.money = "300";
	ch.quest.meeting = "0";
	LAi_SetStayType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 60.0, 60.0);
	n = n + 1;

	makeref(ch,Characters[n]);			// Pepin Bertillon
	ch.name 	= "Пепин";
	ch.lastname 	= "Бертильон";
	ch.id		= "Pepin Bertillon";
	ch.model = "man3";
	ch.sex = "man";
	ch.sound_type = "pirate";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	GiveItem2Character(ch, GUN_COMMON);
	ch.equip.gun = GUN_COMMON;
	ch.location	= "none";
	ch.location.group = "";
	ch.location.locator = "";
	ch.Dialog.Filename = "Pepin Bertillon_dialog.c";
	ch.rank 	= 4;
	ch.reputation = "30";
	ch.experience = "0";
	ch.skill.Leadership = "4";
	ch.skill.Fencing = "5";
	ch.skill.Sailing = "0";
	ch.skill.Accuracy = "0";
	ch.skill.Cannons = "0";
	ch.skill.Grappling = "0";
	ch.skill.Repair = "0";
	ch.skill.Defence = "0";
	ch.skill.Commerce = "4";
	ch.skill.Sneak = "0";
	ch.money = "1500";
	ch.quest.meeting = "0";
	LAi_SetStayType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 90.0, 90.0);
	ch.greeting = "Gr_Pepin Bertillon";
	n = n + 1;

	makeref(ch,Characters[n]);			// Bertillon's guard 1
	ch.name 	= "Телохранитель Бертильона";
	ch.lastname 	= "";
	ch.id		= "Bertillon's guard1";
	ch.model = "pirat2";
	ch.sex = "man";
	ch.sound_type = "pirate";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "none";
	ch.location.group = "";
	ch.location.locator = "";
	ch.Dialog.Filename = "Bertillon's Guard_dialog.c";
	ch.greeting = "Gr_Bertillon's Guard";
	ch.rank 	= 2;
	ch.reputation = "30";
	ch.experience = "0";
	ch.skill.Leadership = "4";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "0";
	ch.skill.Accuracy = "0";
	ch.skill.Cannons = "0";
	ch.skill.Grappling = "0";
	ch.skill.Repair = "0";
	ch.skill.Defence = "0";
	ch.skill.Commerce = "0";
	ch.skill.Sneak = "0";
	ch.money = "500";
	ch.quest.meeting = "0";
	LAi_SetStayType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 70.0, 70.0);
	n = n + 1;

	makeref(ch,Characters[n]);			// Bertillon's guard 2
	ch.name 	= "Телохранитель Бертильона";
	ch.lastname 	= "";
	ch.id		= "Bertillon's guard2";
	ch.model = "pirat4";
	ch.sex = "man";
	ch.sound_type = "pirate";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "none";
	ch.location.group = "";
	ch.location.locator = "";
	ch.Dialog.Filename = "Bertillon's Guard_dialog.c";
	ch.greeting = "Gr_Bertillon's Guard";
	ch.rank 	= 2;
	ch.reputation = "30";
	ch.experience = "0";
	ch.skill.Leadership = "4";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "0";
	ch.skill.Accuracy = "0";
	ch.skill.Cannons = "0";
	ch.skill.Grappling = "0";
	ch.skill.Repair = "0";
	ch.skill.Defence = "0";
	ch.skill.Commerce = "0";
	ch.skill.Sneak = "0";
	ch.money = "500";
	ch.quest.meeting = "0";
	LAi_SetStayType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 70.0, 70.0);
	n = n + 1;

	makeref(ch,Characters[n]);			// Vito Leone
	ch.name 	= "Вито";
	ch.lastname 	= "Леон";
	ch.id		= "Vito Leone";
	ch.model = "Old_man1";
	ch.sex = "man";
	ch.sound_type = "pirate";
	ch.location	= "none";
	ch.location.group = "";
	ch.location.locator = "";
	ch.Dialog.Filename = "Vito Leone_dialog.c";
	ch.rank 	= 7;
	ch.reputation = "70";
	ch.experience = "0";
	ch.skill.Leadership = "8";
	ch.skill.Fencing = "6";
	ch.skill.Sailing = "0";
	ch.skill.Accuracy = "0";
	ch.skill.Cannons = "0";
	ch.skill.Grappling = "0";
	ch.skill.Repair = "0";
	ch.skill.Defence = "0";
	ch.skill.Commerce = "6";
	ch.skill.Sneak = "0";
	ch.money = "7000";
	ch.quest.meeting = "0";
	LAi_SetStayType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 90.0, 90.0);
	ch.greeting = "Gr_Vito Leone";
	n = n + 1;

//Hitman

	//Lucas

	makeref(ch,Characters[n]);			// Joaquin Da Saldanha
	ch.name 	= "Жакуин";
	ch.lastname 	= "Да Сальданья";
	ch.id		= "Joaquin Da Saldanha";
	ch.model = "admiral";
	ch.sex = "man";
	ch.sound_type = "pirate";
	GiveItem2Character(ch, BLADE_LONG);
	ch.equip.blade = BLADE_LONG;
	GiveItem2Character(ch, GUN_COMMON);
	ch.equip.gun = GUN_COMMON;
	ch.location	= "None";
	ch.location.group = "goto";
	ch.location.locator = "goto6";
	ch.Dialog.Filename = "Joaquin Da Saldanha_dialog.c";
	ch.rank 	= 10;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "8";
	ch.skill.Fencing = "5";
	ch.skill.Sailing = "3";
	ch.skill.Accuracy = "4";
	ch.skill.Cannons = "4";
	ch.skill.Grappling = "6";
	ch.skill.Repair = "3";
	ch.skill.Defence = "4";
	ch.skill.Commerce = "5";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetStayType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 120.0, 120.0);
	n = n + 1;

	makeref(ch,Characters[n]);			// Arabella Silehard
	ch.name 	= "Арабелла";
	ch.lastname 	= "Сайлхард";
	ch.id		= "Arabella Silehard";
	ch.model = "towngirl1";
	ch.sex = "woman";
	ch.sound_type = "pirate";
	ch.location	= "none";
	ch.location.group = "goto";
	ch.location.locator = "goto11";
	ch.Dialog.Filename = "Arabella Silehard_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "60";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "3";
	ch.skill.Sneak = "1";
	ch.money = "500";
	ch.quest.meeting = "0";
	LAi_SetStayType(ch);
	LAi_SetLoginTime(ch, 8.0, 20.0);
	LAi_SetHP(ch, 40.0, 40.0);
	ch.greeting = "Gr_Arabella Silehard";
	n = n + 1;

	makeref(ch,Characters[n]);			// Arabella's Guard 1
	ch.name 	= "Телохранитель Арабеллы";
	ch.lastname 	= "";
	ch.id		= "Arabella's guard 1";
	ch.model = "offic_eng";
	ch.sex = "man";
	ch.sound_type = "pirate";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	GiveItem2Character(ch, GUN_COMMON);
	ch.equip.gun = GUN_COMMON;
	ch.location	= "none";
	ch.location.group = "";
	ch.location.locator = "";
	ch.Dialog.Filename = "Arabella's guard_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "50";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "4";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "5";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "100";
	ch.quest.meeting = "0";
	LAi_SetStayType(ch);
	LAi_SetLoginTime(ch, 8.0, 20.0);
	LAi_SetHP(ch, 80.0, 80.0);
	ch.greeting = "Gr_Arabella's guard";
	n = n + 1;

	makeref(ch,Characters[n]);			// Arabella's Guard 2
	ch.name 	= "Телохранитель Арабеллы";
	ch.lastname 	= "";
	ch.id		= "Arabella's guard 2";
	ch.model = "offic_eng";
	ch.sex = "man";
	ch.sound_type = "pirate";
	GiveItem2Character(ch, BLADE_LONG);
	ch.equip.blade = BLADE_LONG;
	GiveItem2Character(ch, GUN_COMMON);
	ch.equip.gun = GUN_COMMON;
	ch.location	= "none";
	ch.location.group = "";
	ch.location.locator = "";
	ch.Dialog.Filename = "Arabella's guard_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "50";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "4";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "5";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "100";
	ch.quest.meeting = "0";
	LAi_SetStayType(ch);
	LAi_SetLoginTime(ch, 8.0, 20.0);
	LAi_SetHP(ch, 80.0, 80.0);
	ch.greeting = "Gr_Arabella's guard";
	n = n + 1;

	makeref(ch,Characters[n]);			// Ransom Pirate 1
	ch.name 	= "Билли";
	ch.lastname 	= "Брок";
	ch.id		= "Billy Brock";
	ch.model = "korsar";
	ch.sex = "man";
	ch.sound_type = "pirate";
	GiveItem2Character(ch, BLADE_LONG);
	ch.equip.blade = BLADE_LONG;
	GiveItem2Character(ch, GUN_COMMON);
	ch.equip.gun = GUN_COMMON;
	ch.location = "none";
	ch.location.group = "goto";
	ch.location.locator = "goto3";
	ch.Dialog.Filename = "Billy Brock_dialog.c";
	ch.greeting = "Gr_Billy Brock";
	ch.rank 	= 1;
	ch.reputation = "50";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "4";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "5";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "100";
	ch.quest.meeting = "0";
	LAi_SetStayType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 70.0, 70.0);
	n = n + 1;

	makeref(ch,Characters[n]);			// Ransom Pirate 2
	ch.name 	= "Снорри";
	ch.lastname 	= "Балдурсон";
	ch.id		= "Snorri Baldursson";
	ch.model = "sailor6";
	ch.sex = "man";
	ch.sound_type = "pirate";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "none";
	ch.location.group = "goto";
	ch.location.locator = "goto2";
	ch.Dialog.Filename = "Snorri Baldursson_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "50";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "4";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "5";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "100";
	ch.quest.meeting = "0";
	LAi_SetStayType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 50.0, 50.0);
	n = n + 1;

	makeref(ch,Characters[n]);			// Ransom Pirate 3
	ch.name 	= "Франсис";
	ch.lastname 	= "Снейк";
	ch.id		= "Francis Snake";
	ch.model = "corsair1_1";
	ch.sex = "man";
	ch.sound_type = "pirate";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "none";
	ch.location.group = "";
	ch.location.locator = "";
	ch.Dialog.Filename = "";
	ch.rank 	= 1;
	ch.reputation = "50";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "4";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "5";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "100";
	ch.quest.meeting = "0";
	LAi_SetStayType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 50.0, 50.0);
	n = n + 1;

//Lucas

	//Tutorial

	makeref(ch,Characters[n]);			// Malcolm Hatcher
	ch.name 	= "Малькольм";
	ch.lastname 	= "Хатчер";
	ch.id		= "Malcolm Hatcher";
	ch.model = "bocman3";
	ch.sex = "man";
	ch.sound_type = "pirate";
	GiveItem2Character(ch, "blade20");
	ch.equip.blade = "blade20";
	ch.location	= "none";
	ch.location.group = "";
	ch.location.locator = "";
	ch.Dialog.Filename = "Malcolm Hatcher_dialog.c";
	ch.greeting = "Gr_Malcolm Hatcher";
	ch.rank 	= 7;
	ch.reputation = "30";
	ch.experience = "0";
	ch.skill.Leadership = "0";
	ch.skill.Fencing = "10";
	ch.skill.Sailing = "6";
	ch.skill.Accuracy = "3";
	ch.skill.Cannons = "3";
	ch.skill.Grappling = "4";
	ch.skill.Repair = "5";
	ch.skill.Defence = "4";
	ch.skill.Commerce = "2";
	ch.skill.Sneak = "1";
	ch.money = "500";
	ch.quest.meeting = "0";
	LAi_SetWarriorTypeNoGroup(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 400.0, 400.0);
	n = n + 1;

//Tutorial

// Edgar Attwood quest

		makeref(ch,Characters[n]);			// Martin Warner.
	ch.name 	= "Мартин";
	ch.lastname 	= "Уорнер";
	ch.id		= "Martin Warner";
	ch.model = "soldier_Eng2";
	ch.sex = "man";
	ch.location	= "None";
	ch.location.group = "sit";
	ch.location.locator = "sit4";
	ch.Dialog.Filename = "soldier2.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetSitType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	ch.greeting = "Gr_soldier2";
	n = n + 1;

	makeref(ch,Characters[n]);			// Jack Greenfield.
	ch.name 	= "Джек";
	ch.lastname 	= "Гринфилд";
	ch.id		= "Jack Greenfield";
	ch.model = "soldier_Eng3";
	ch.sex = "man";
	ch.location	= "none";
	ch.location.group = "sit";
	ch.location.locator = "sit5";
	ch.Dialog.Filename = "soldier1.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.Ship.Name = "Prison ship";
	ch.Ship.Type = SHIP_BRIG_ENGLAND;
	ch.Ship.Stopped = true;
	ch.Ship.Cannons.Type = CANNON_TYPE_CANNON_LBS12;
	LAi_SetSitType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	ch.greeting = "Gr_soldier1";
	n = n + 1;

	makeref(ch,Characters[n]);			// zek
	ch.name 	= "";
	ch.lastname 	= "";
	ch.id		= "zek";
	ch.model = "man2";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	ch.location	= "none";
	ch.location.group = "goto";
	ch.location.locator = "goto5";
	ch.Dialog.Filename = "";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetCitizenType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	n = n + 1;


	makeref(ch,Characters[n]);			// zek
	ch.name 	= "";
	ch.lastname 	= "";
	ch.id		= "zek2";
	ch.model = "man4";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	ch.location	= "none";
	ch.location.group = "goto";
	ch.location.locator = "goto5";
	ch.Dialog.Filename = "";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetCitizenType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	n = n + 1;

// Edgar Attwood quest


//Cursed Coins Quest

	makeref(ch,Characters[n]);			// First Cursed Pirate
	ch.name 	= "Проклятый";
	ch.lastname 	= "Пират";
	ch.id		= "Cursed_Pirate_01";
	ch.model = "man5_1";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	ch.location	= "none";
	ch.location.group = "goto";
	ch.location.locator = "goto5";
	ch.Dialog.Filename = "CursedPirate_Dialog.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "2";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetWarriorType(ch);
	LAi_warrior_SetStay(ch, true);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_SetImmortal(ch, true);
	TakeNItems(ch,"blade1", 1);
	EquipCharacterByItem(Ch, "blade1");
	ch.greeting = "Gr_CursedPirate";
	n = n + 1;

	makeref(ch,Characters[n]);			// Second Cursed Pirate
	ch.name 	= "Проклятый";
	ch.lastname 	= "Пират";
	ch.id		= "Cursed_Pirate_02";
	ch.model = "bocman4";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	ch.location	= "none";
	ch.location.group = "goto";
	ch.location.locator = "goto5";
	ch.Dialog.Filename = "CursedPirate_Dialog.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "2";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetWarriorType(ch);
	LAi_warrior_SetStay(ch, true);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_SetImmortal(ch, true);
	TakeNItems(ch,"blade1", 1);
	EquipCharacterByItem(Ch, "blade1");
	ch.greeting = "Gr_CursedPirate";
	n = n + 1;

	makeref(ch,Characters[n]);			// Big Boss.
	ch.name 	= "Большой";
	ch.lastname 	= "Босс";
	ch.id		= "Big Boss";
	ch.model = "soldier_Eng3";
	ch.sex = "man";
	ch.location	= "none";
	ch.location.group = "sit";
	ch.location.locator = "sit5";
	ch.Dialog.Filename = "soldier1.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.Ship.Name = "Black pearl";
	ch.Ship.Type = SHIP_BLACK_PEARL;
	ch.Ship.Stopped = true;
	LAi_SetSitType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	ch.greeting = "Gr_soldier1";
	n = n + 1;

	makeref(ch,Characters[n]);			// Henry Peat
	ch.name 	= "Генри";
	ch.lastname 	= "Пит";
	ch.id		= "Henry Peat";
	ch.model = "old_man2";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	ch.location	= "None";
	ch.location.group = "sit";
	ch.location.locator = "sit1";
	ch.Dialog.Filename = "Henry Peat_dialog.c";
	ch.greeting = "Gr_Henry Peat";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "2";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetSitType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	n = n + 1;

	makeref(ch,Characters[n]);			// Gordon Carpenter
	ch.name 	= "Гордон";
	ch.lastname 	= "Карпентер";
	ch.id		= "Gordon Carpenter";
	ch.model = "bocman4";
	ch.sex = "man";
	ch.sound_type = "old_man2";
	ch.location	= "None";
	ch.location.group = "sit";
	ch.location.locator = "sit1";
	ch.Dialog.Filename = "Gordon Carpenter_dialog.c";
	ch.greeting = "Gr_Gordon Carpenter";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "2";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetCitizenType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	n = n + 1;

	makeref(ch,Characters[n]);			// ANIMISTS
	ch.name 	= "Капитан";
	ch.lastname 	= "";
	ch.id		= "Dark Captain";
	ch.model = "ANIMISTS2";
	ch.sex = "man";
	ch.sound_type = "pirate";
	LAi_NoRebirthEnable(ch);
	ch.Ship.AI.GroupName = "Ethilrede Claar";
	ch.Ship.AI.Task = "attack";
	ch.nation = PIRATE;
	GiveItem2Character(ch, BLADE_LONG);
	ch.equip.blade = BLADE_LONG;
	ch.location	= "none";
	ch.location.group = "";
	ch.location.locator = "";
	ch.Dialog.Filename = "Gyles Dubois_dialog.c";
	ch.Ship.Name = "Mefisto";
	ch.Ship.Type = SHIP_FRIGATE_SAT;
	ch.Ship.Stopped = true;
	ch.Ship.Cannons.Type = CANNON_TYPE_CANNON_LBS24;
	ch.rank 	= 1;
	ch.reputation = "1";
	ch.experience = "0";
	ch.skill.Leadership = "8";
	ch.skill.Fencing = "10";
	ch.skill.Sailing = "9";
	ch.skill.Accuracy = "8";
	ch.skill.Cannons = "9";
	ch.skill.Grappling = "3";
	ch.skill.Repair = "1";
	ch.skill.Defence = "4";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "8";
	ch.money = "10";
	LAi_SetMerchantType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	ch.greeting = "Gr_Gyles Dubois";
	n = n + 1;

	makeref(ch,Characters[n]);			// Giraldo Figuiera
	ch.name 	= "Джиральдо";
	ch.lastname 	= "Фигуейра";
	ch.id		= "Giraldo Figuiera";
	ch.model = "corsar2";
	ch.sex = "man";
	ch.sound_type = "pirate";
	LAi_NoRebirthEnable(ch);
	ch.Ship.AI.GroupName = "Ethilrede Claar";
	ch.Ship.AI.Task = "attack";
	ch.nation = PIRATE;
	GiveItem2Character(ch, BLADE_LONG);
	ch.equip.blade = BLADE_LONG;
	ch.location	= "none";
	ch.location.group = "Quest_ships";
	ch.location.locator = "quest_ship_11";
	ch.Dialog.Filename = "Gyles Dubois_dialog.c";
	ch.Ship.Name = "Mefisto";
	ch.Ship.Type = SHIP_FRIGATE_SAT;
	ch.Ship.Stopped = true;
	ch.Ship.Cannons.Type = CANNON_TYPE_CANNON_LBS24;
	ch.rank 	= 1;
	ch.reputation = "1";
	ch.experience = "0";
	ch.skill.Leadership = "8";
	ch.skill.Fencing = "10";
	ch.skill.Sailing = "9";
	ch.skill.Accuracy = "8";
	ch.skill.Cannons = "9";
	ch.skill.Grappling = "3";
	ch.skill.Repair = "1";
	ch.skill.Defence = "4";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "8";
	ch.money = "10";
	LAi_SetMerchantType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	ch.greeting = "Gr_Gyles Dubois";
	n = n + 1;

	makeref(ch,Characters[n]);			// Giraldo Figuiera
	ch.name 	= "Торговец";
	ch.lastname 	= "";
	ch.id		= "Quest trader";
	ch.model = "storeman2";
	ch.sex = "man";
	ch.sound_type = "seaman";
	ch.nation = ENGLAND;
	GiveItem2Character(ch, BLADE_LONG);
	ch.equip.blade = BLADE_LONG;
	ch.location	= "none";
	ch.location.group = "";
	ch.location.locator = "";
	ch.Dialog.Filename = "anacleto_dialog.c";
	ch.Ship.Name = "";
	ch.Ship.Type = SHIP_SLOOP_ENGLAND;
	ch.Ship.Stopped = true;
	ch.Ship.Cannons.Type = CANNON_TYPE_CANNON_LBS12;
	ch.rank 	= 1;
	ch.reputation = "1";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "3";
	ch.skill.Accuracy = "3";
	ch.skill.Cannons = "3";
	ch.skill.Grappling = "0";
	ch.skill.Repair = "4";
	ch.skill.Defence = "4";
	ch.skill.Commerce = "5";
	ch.skill.Sneak = "0";
	ch.money = "1";
	LAi_SetActorType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	ch.greeting = "Gr_Anacleto";
	n = n + 1;

	makeref(ch,Characters[n]);		//первый капитан-мститель за поруганнцю честь ростовщика
	ch.name 	= " ";
	ch.lastname = " ";
	ch.id		= "Usurer_Avenger01";
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "None";
	ch.location.group = "";
	ch.location.locator = "";
	ch.reputation = "50";
	ch.experience = 0;
	ch.Ship.Name = "Dolphine";
	ch.Ship.Type = SHIP_LUGGER_ENGLAND;
	ch.Ship.Cannons.Type = CANNON_TYPE_CANNON_LBS24;
	ch.ship.cargo.goods.bombs = 1000;
	ch.Ship.Stopped = false;
	LAi_SetWarriorType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	n = n + 1;

	makeref(ch,Characters[n]);		//второй капитан-мститель за поруганнцю честь ростовщика
	ch.name 	= " ";
	ch.lastname = " ";
	ch.id		= "Usurer_Avenger02";
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "None";
	ch.location.group = "";
	ch.location.locator = "";
	ch.reputation = "50";
	ch.experience = 0;
	ch.Ship.Name = "Dolphine";
	ch.Ship.Type = SHIP_LUGGER_ENGLAND;
	ch.Ship.Cannons.Type = CANNON_TYPE_CANNON_LBS24;
	ch.ship.cargo.goods.bombs = 1000;
	ch.Ship.Stopped = false;
	LAi_SetWarriorType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	n = n + 1;

	makeref(ch,Characters[n]);		//третий капитан-мститель за поруганнцю честь ростовщика
	ch.name 	= " ";
	ch.lastname = " ";
	ch.id		= "Usurer_Avenger03";
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "None";
	ch.location.group = "";
	ch.location.locator = "";
	ch.reputation = "50";
	ch.experience = 0;
	ch.Ship.Name = "Dolphine";
	ch.Ship.Type = SHIP_LUGGER_ENGLAND;
	ch.Ship.Cannons.Type = CANNON_TYPE_CANNON_LBS24;
	ch.ship.cargo.goods.bombs = 1000;
	ch.Ship.Stopped = false;
	LAi_SetWarriorType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	n = n + 1;


	return n;
}
	